### ISSUE TITLE
Homepage Logo and Text

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#117]
We need to replace the ABC logo as well as add some introduction text to welcome users that will appear above the "Featured Items" text.

**Comment by neelusingh28** [comment]
Q1. Can we know how the logo will look like now?
Q2. Can we know the text content to validate?
Q3. Will clicking on logo bring the user back to the homepage?

**Comment by llin-freeman** [comment]
Hi Neelu, I'm working on the text--should have something tomorrow.  Re: Logo, no image yet.  Yes, clicking on the logo should bring them back to the homepage. Thanks!

**Comment by llin-freeman** [comment]
Here are the logos for the page.  Emailed UI team for incorporation.
![ca dgs logo](https://cloud.githubusercontent.com/assets/22507715/23266287/61930726-f9b5-11e6-8e43-bd9df642e93e.png)
![ca dot logo](https://cloud.githubusercontent.com/assets/22507715/23266291/65ab5322-f9b5-11e6-8ae5-8fbcee6c793f.png)

**Comment by jennymnh** [comment]
Ended up adding the DGS logo, because the other one didn't seem to fit in with the theme
![image](https://cloud.githubusercontent.com/assets/9370407/23269738/883d69f2-f9bf-11e6-92e5-0045acf15162.png)

one I didn't use -
![image](https://cloud.githubusercontent.com/assets/9370407/23269634/39ef81e0-f9bf-11e6-9a90-a1c2a2c01191.png)

**Comment by jennymnh** [comment]
Closing this out since it is done. I think I may have forgotten to do that in the last sprint.
