### ISSUE TITLE
Issue #115 - Search/Edit/Delete Items in a Catalog functionality is NOT working

### ISSUE THREAD

**Issue by neelusingh28** [FEISystems/ca-adpq-prototype#154]
User: Admin1

- [x] 1. Edit - Save changes button is not working if any values are changed
- [x] 2. Search is working only when nothing is selected in cells
- [x] 3. select some filelds click on search>no result>Click on search in left >system does not empty the cells
- [ ] 4. Product Image - Browse for image - is not available on the search page
- [x] 5. When delete selected then system displays following message - UnauthorizedAccessException: Attempted to perform an unauthorized operation.
- [x] 6. User does not have an option to delete multiple items

- [x] 7. Noticed one more thing that Cancel and Save Changes buttons are not aligned.

**Comment by lutech** [comment]
User: Admin1

- [x] 1. Edit - Save changes button is not working if any values are changed
- Verified it is working. All fields are required. Sometimes the UNSPSC field is empty by default. Populating data in  the UNSPSC field enables the Save button. There should be another task to make this field optional.
- [x] 2. Search is working only when nothing is selected in cells
- Resolved. Fields require an exact match. Although it is not clear, this is a known behaviour. To do fuzzy search, you can append and preppend %. Example: %AMD%. Fixed issue related to deleting previously populated filters. The DB did not like empty filters like "" due to it attempting to search exact matches.
- [x] 3. select some filelds click on search>no result>Click on search in left >system does not empty the cells
- Results should now appear. The second issue is not a bug but a question of preference. For usability purposes, we should keep the fields pre-populated with the previous search criteria in case they want to narrow thier search.
- [x] 5. When delete selected then system displays following message - UnauthorizedAccessException: Attempted to perform an unauthorized operation.
- Issue was related to #155. Unauthorized user should no longer have access to thes functions.
- [x] 6. User does not have an option to delete multiple items

**Comment by lutech** [comment]
@davidatfei @ClaireReinken I was able to resolve some of the issues but the 2 below would require back end work.  Not sure if they're exactly necessary however. As they're in the requirements in #115, I will let Claire decide if these are truly necessary. @ClaireReinken , can you please confirm?
- [ ] 4. Product Image - Browse for image - is not available on the search page
- [x] 6. User does not have an option to delete multiple items

**Comment by ClaireReinken** [comment]
4. Product Image - Browse for image - is not available on the search page
 6. User does not have an option to delete multiple items
These are nice to have at this point. Let's remove them from the acceptance criteria. I will move this issue to QC Doing.

**Comment by davidatfei** [comment]
I added the ability to delete multiple items. I also added the image file name box to the search page.  I don’t know if that is what was intended by #4, but that’s what I did.

I could not get a checkbox to display, so I just use <a>s with text that toggles between Selected and Unselected.  UI people, feel free to change that.

One of the reports (Trend I think) says to initially select the current Fiscal Quarter date range.  I need the rules you want me to use for determining the fiscal quarter based on a calendar date.

**Comment by ClaireReinken** [comment]
Let's make the fiscal quarter a calendar quarter.

FY Q1 = Jan - march
FY Q2= April - June
FY Q3 = July - Sept
FY Q4 = Oct - Dec

- Claire Reinken

On Feb 26, 2017, at 4:55 PM, davidatfei <notifications@github.com<mailto:notifications@github.com>> wrote:

I added the ability to delete multiple items. I also added the image file name box to the search page. I don't know if that is what was intended by #4, but that's what I did.

I could not get a checkbox to display, so I just use <a>s with text that toggles between Selected and Unselected. UI people, feel free to change that.

One of the reports (Trend I think) says to initially select the current Fiscal Quarter date range. I need the rules you want me to use for determining the fiscal quarter based on a calendar date.

**Comment by llin-freeman** [comment]
Hi,
I thought we were using a date range, so the user selects start & end date for the desired report.  That reduces the risk of calendar vs fiscal year issues.

Thanks


Get Outlook for iOS<https://aka.ms/o0ukef>




On Sun, Feb 26, 2017 at 4:59 PM -0500, "ClaireReinken" <notifications@github.com<mailto:notifications@github.com>> wrote:

Let's make the fiscal quarter a calendar quarter.

FY Q1 = Jan - march
FY Q2= April - June
FY Q3 = July - Sept
FY Q4 = Oct - Dec

- Claire Reinken

On Feb 26, 2017, at 4:55 PM, davidatfei <notifications@github.com<mailto:notifications@github.com>> wrote:

I added the ability to delete multiple items. I also added the image file name box to the search page. I don't know if that is what was intended by #4, but that's what I did.

I could not get a checkbox to display, so I just use <a>s with text that toggles between Selected and Unselected. UI people, feel free to change that.

One of the reports (Trend I think) says to initially select the current Fiscal Quarter date range. I need the rules you want me to use for determining the fiscal quarter based on a calendar date.

**Comment by neelusingh28** [comment]
User: Admin1

Above issues are fixed but found following issues now. 

1. Pagination issue - Search always displays Page # of 44 even though there are less products available.

2. Image appears only if user hits on edit button and then comes back on left menu search. After that clear search button does not clear image. 

3. Inventory display issue - Dell is 248 but search bringing only 10 results, Services are 99 in data set but displaying only 90

4. Contract Expiration field does NOT bring any results. Tried 6/10/2017 & 6-10-2017

5. Search>Edit - I think there should be 'Cancel' button if in case user does not want to save and comes out of that screen.

6. Should we expand cells width when text is larger? Please check screenshot

![image](https://cloud.githubusercontent.com/assets/25771656/23368558/3eb6222c-fcdc-11e6-816b-589c9b9a4a48.png)

**Comment by davidatfei** [comment]
1. Fixed
2. Fixed
3. Cannot duplicate
4. Try yyyy-mm-dd. Maybe the UI people can change this to a date picker.
5. Added Cancel button. Changes to styling are causing the placement to be weird. UI people should address.
6. Question for UI people.

**Comment by jennymnh** [comment]
@christianhfei  will take a look, thanks.

**Comment by christianhfei** [comment]
Checkbox issue is resolved, the USA stylesheet's custom checkbox styles were hiding the real checkbox, so I just removed them. This will only apply to the checkboxes inside tables in the admin catalog section.

https://github.com/FEISystems/ca-adpq-prototype/commit/9a4cf4e9f4ee8a2ef0ec3c49edb8af1f7e005ad8

**Comment by neelusingh28** [comment]
All above issues are fixed but found following issues now.

1. After search results if clicked on browser back arrow, system takes the user to the Admin home page instead of search page.
2. Edit Product - if Product does not have UNSPSC then system is forcing user to enter that until that 'Save' button does not get activated.
3. Save changes button not saving changes. generating error.
4. Delete  link deleting item but displaying error.

![image](https://cloud.githubusercontent.com/assets/25771656/23473970/289296b0-fe80-11e6-9420-f4d9b13eeae3.png)

**Comment by davidatfei** [comment]
1. When on the reports page, Back is the Admin home page.
2. It is being treated as a required column. If you have requirements that say otherwise, please provide.
3. Cannot duplicate. Try to login as an admin.
4. Cannot duplicate. Try to login as an admin.

If you are encountering the unauthorized operation errors after signing in as an admin, please write down detailed steps to reproduce the problem.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site and working as expected in Chrome & Firefox.
