### ISSUE TITLE
Log in credentials does not work as expected

### ISSUE THREAD

**Issue by neelusingh28** [FEISystems/ca-adpq-prototype#163]
1. There is no way to figure it out what user you have logged in as unless user clicks on log out and place cursor in user id field
2. Chrome remembers the user id and password but correct password is not remembered and log in fails unless user enters correct password.
3. I think we should have labels too as user name and password too on log in screen. 
4. Cart and Compare list links displays results if  opened on same page after adding items if in case user clicks on   'open link in new tab' then Cart and Compare list does not displays any results, looks like it kicks out the user from log in.

**Comment by JXPrime** [comment]
1 - in the main-nav component can we add something to the model behind to show login/logout depending on status?
2 - no clue what's up with this
3 - There are labels (in modal.component), but they have a class "sr-only", @lnajera @lutech ?
4 - can't reproduce this.

**Comment by lutech** [comment]
1- If we need to how account info in the header, we will need a separate requirement/story. Not sure there is enough time. @ClaireReinken , a story can be created and we can try to get to it.
2 -This might be only on your browser. You may have "saved" the incorrect password to chrome. Try cleaning/deleting from browser history.
3 -We can show the labels. @JXPrime , "sr-only" is a way to hide visually, but keep accessible to screen-readers. Its just absolute positioning off the screen. I will assign to @kcallander  to show the labels. 
4 -The Compare List is "per session", since we are not storing to a DB. Creating new tab creates a new "session". This seems like an edge case we probably don't have to handle for the purposes of this prototype. Cart works fine as it is stored in DB. Could not reproduce it disappearing in new tab.

**Comment by ClaireReinken** [comment]
1- If we need to how account info in the header, we will need a separate requirement/story. Not sure there is enough time. @ClaireReinken , a story can be created and we can try to get to it. I'll make a separate story and we'll put this low on the board.

**Comment by kcallander** [comment]
I removed the class "sr-only" and you can see form labels now.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site and working as expected in Chrome, Firefox, IE and devices.
