### ISSUE TITLE
Authorized User Story 2 - Advanced Search

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#17]
As an Authorized User, I want to use advanced search  by using filters so I can have more specific search result

Acceptance Criteria:
•	User can search by one or combination of following filters:
* Product title /description
o	Category
o	Price (range)
o	Manufacturer
o	Manufacturer Part Number (OEM #)
o	SKU#/Item#
•	System display search result (refer to search result user story) 
* contract number
* vendor name

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues #82 and #83

**Comment by JXPrime** [comment]
@ClaireReinken to clarify, these would be considered an "AND" search, where the quick search is an "OR" search? ie, if I put in both a category and a minimum price, it will only show products that meet both criteria, correct?

**Comment by ClaireReinken** [comment]
Correct. Also, the user can select enter search parameters associated with different fields, like a SKU, contract number, etc.

**Comment by neelusingh28** [comment]
**Bug Details:**

1. None of the field is working in advance search. No results returned. 
2. Clear button does not clear if any value selected in Price
3. Looks like Keyword field is renamed to Product Name? Is that expected?
4. Availability field is no more there? Is that expected?
5. As per data set spreadsheet Manufacturer drop down should have 6 line items but it displays only 2.
6. Category drop down is different from the mock up. Please check screenshot. Is that expected? 

Prototype Screenshot:
![image](https://cloud.githubusercontent.com/assets/25771656/23276605/f4843208-f9d8-11e6-949a-963fcc424a6f.png)

Mock up screenshot
![image](https://cloud.githubusercontent.com/assets/25771656/23276590/e483d19c-f9d8-11e6-9a25-485973de154d.png)

**Comment by ClaireReinken** [comment]
Bug Details:
1.None of the field is working in advance search. No results returned.
2.Clear button does not clear if any value selected in Price
3.Looks like Keyword field is renamed to Product Name? Is that expected? - Yes, I discussed with dev. This is expected behavior 
4.Availability field is no more there? Is that expected? - Yes, we will assume all items are in stock for the purposes of the prototype. 
5.As per data set spreadsheet Manufacturer drop down should have 6 line items but it displays only 2. - It should list all available manufacturers, so more than 2. - Lisa will send you the complete list. 
6.Category drop down is different from the mock up. Please check screenshot. Is that expected? - Yes

**Comment by JXPrime** [comment]
Fixed clear button to clear price selection. @neelusingh28

**Comment by neelusingh28** [comment]
Bug #176

**Comment by neelusingh28** [comment]
@ClaireReinken - Manufacturer Part Number (OEM #) & SKU # are same for every product - Do we really need both on advance search?

**Comment by ClaireReinken** [comment]
@ClaireReinken - Manufacturer Part Number (OEM #) & SKU # are same for every product - Do we really need both on advance search? - Yes because the government provides both columns of text and they may differ for future items.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.
