### ISSUE TITLE
Authorized User Story 7 - Manage Shopping Cart

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#22]
As an Authorized User, I want to manage my shopping cart  so I can prepare the order I want to place
Acceptance Criteria:
•	User can view current shopping cart
•	Following info are displayed for items in shopping cart:
o	Item picture
o	Item Description
o	Category
o	Manufacturer
o	Manufacturer Part Number (OEM #)
o	SKU#/Item#
o	Price
o	Quantity
o	Total
o	Order Total
•	User needs to have ability to update quantity or delete an item

**Comment by Mikewilburn302** [comment]
Questions:
1.	Does changing quantity to 0 remove it when cart is updated?
2.	Is there a maximum quantity? Will the application know how many are in stock?
3.	Is there a “Continue Shopping” button?
4.	Does clicking on an item in the cart open the item details?

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues #94 and #95

**Comment by kcallander** [comment]
@ClaireReinken @lnajera @jennymnh - I am thinking about removing the checkboxes and the Remove Items button since we have remove already listed on the right hand side and seems redundant. Any opposition?

**Comment by ClaireReinken** [comment]
@ClaireReinken @lnajera @jennymnh - I am thinking about removing the checkboxes and the Remove Items button since we have remove already listed on the right hand side and seems redundant. Any opposition? None here. I would rather have an "Update Cart" button to allow users to update quantities or remove an item if the quantity is changed to 0.

**Comment by lnajera** [comment]
Team,

We administered evaluation of the web app to 5 participants. Jenny collected notes and it turns out that the majority of users used the Checkbox and Delete button, over the small delete link.

So based on initial testing we should keep this feature and remove the delete link.

Jenny captured lots of notes and will compile them into an organized list over the weekend. Another next step will be to prioritize the modifications to the site based on user testing results.

Thanks

Lud

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Feb 17, 2017 at 3:29 PM -0500, "ClaireReinken" <notifications@github.com<mailto:notifications@github.com>> wrote:


@ClaireReinken<https://github.com/ClaireReinken> @lnajera<https://github.com/lnajera> @jennymnh<https://github.com/jennymnh> - I am thinking about removing the checkboxes and the Remove Items button since we have remove already listed on the right hand side and seems redundant. Any opposition? None here. I would rather have an "Update Cart" button to allow users to update quantities or remove an item if the quantity is changed to 0.

**Comment by ClaireReinken** [comment]
In response to the comment above, the users didn't have an opportunity to test updating quantities. So you are you proposing have an update cart button, remove items button, and a check out button? Isn't that a little busy? I've checked a few existing e commerce sites and none use checkmarks (they all use delete links). I feel that we should not keep the checkmarks because users can either click the remove item link OR change the quantity to 0 to remove an item; do we need a third method to remove items? If UI would like to refine this story further for Sprint 2, let me know and we can discuss on Monday.

**Comment by jennymnh** [comment]
We would not be keeping all three options. Most likely, the "remove items" button will be changed to "update cart" and the remove link will no longer exist. I will mock something up over the weekend for better clarification.

**Comment by ClaireReinken** [comment]
Thank you. Please attach a screenshot of the new mock up to the story and we can provide any feedback as needed.

- Claire Reinken

On Feb 17, 2017, at 7:11 PM, Jenny Ho <notifications@github.com<mailto:notifications@github.com>> wrote:


We would not be keeping all three options. Most likely, the "remove items" button will be changed to "update cart" and the remove link will no longer exist. I will mock something up over the weekend for better clarification.

-

**Comment by jennymnh** [comment]
Here is a mockup of the revised functionality.

![image](https://cloud.githubusercontent.com/assets/9370407/23095905/02aa684a-f5e0-11e6-96f2-4c2277eb6fd7.png)

The "Remove Selected" button has been changed to "Update Cart" and everything else stays the same. This way, a user can update the quantity of several items at one time by utilizing the checkboxes, and still remove items individually if they wish.

Originally I was going to remove the "Remove" link and use the checkboxes for multiple deletion but it ultimately made more sense to let the user update the entire item with it instead.

Also, after brief investigation of other ecommerce sites, a majority of them have the "remove" link for single items, as opposed to a batch removal link.

**Comment by ClaireReinken** [comment]
This looks great but I would still remove the checkboxes as I'm not sure they have a function now. Thanks.

- Claire Reinken

On Feb 18, 2017, at 1:41 PM, Jenny Ho <notifications@github.com<mailto:notifications@github.com>> wrote:


Here is a mockup of the revised functionality.

[image]<https://cloud.githubusercontent.com/assets/9370407/23095844/0e1bec86-f5df-11e6-8f9a-be6de214f44c.png>

The "Remove Selected" button has been changed to "Update Cart" and everything else stays the same. This way, a user can update the quantity of several items at one time by utilizing the checkboxes, and still remove items individually if they wish.

Originally I was going to remove the "Remove" link and use the checkboxes for multiple deletion but it ultimately made more sense to let the user update the entire item with it instead.

Also, after brief investigation of other ecommerce sites, a majority of them have the "remove" link for single items, as opposed to a batch removal link.

-

**Comment by neelusingh28** [comment]
**Bug Details:**

1. Once item added to cart then Cart button on top does not display any #
2. I don't think we need update cart button since we have drop down with maximum 6 quantities and price is changing on changing qty

**Comment by jennymnh** [comment]
When I was mocking up the application page with dummy data, I added a random quantity amount to the dropdown (6), should it still be kept that way? Or should we change it to a text box so users can enter however many?

**Comment by ClaireReinken** [comment]
When I was mocking up the application page with dummy data, I added a random quantity amount to the dropdown (6), should it still be kept that way? Or should we change it to a text box so users can enter however many? - I would change this to a text box. They might be placing large orders.

**Comment by ClaireReinken** [comment]
2.I don't think we need update cart button since we have drop down with maximum 6 quantities and price is changing on changing qty - Jenny is changing to a text box since I believe they will need to add more than 6 items for large orders.

**Comment by jennymnh** [comment]
- [ ] Quantity needs to be a textbox
- [ ] Add total cost to the bottom of the page
- [ ] Remove help information
- [ ] Add total cost of each item

**Comment by lutech** [comment]
@jennymnh , lets go over this one together.
