### ISSUE TITLE
Authorized User Story 10 - Cancel Order

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#25]
As an Authorized User, I want to cancel an order to stop the order processing process

Acceptance Criteria:
•	User should able to cancel an order if order status is “Pending” or Under Review”
•	User should not cancel an order with status = confirmed/shipped/delivered
•	Once cancelled successfully, system sent notification email to user’s email in order details

**Comment by neelusingh28** [comment]
Q1. On cancelling how payment will be refunded? Through same mode of payment or Gift card? Will there be an email notification to consumer about this?
Q2. In how many days payment would be refunded? Will there be an email notification to consumer about this?
Q3. If order status is confirmed/shipped/delivered - can it be returned? If yes, how ? Free Return shipping OR will certain cost be deducted from payment received?
Q4. Can order be placed again once cancelled? 
Q5. Can an order be cancelled over the phone?

**Comment by ClaireReinken** [comment]
Q1. On cancelling how payment will be refunded? Through same mode of payment or Gift card? Will there be an email notification to consumer about this? - Via the same payment method. No confirmation email for the prototype. 
 Q2. In how many days payment would be refunded? Will there be an email notification to consumer about this? - 1 says should be sufficient for the prototype
 Q3. If order status is confirmed/shipped/delivered - can it be returned? If yes, how ? Free Return shipping OR will certain cost be deducted from payment received? - The prototype will not include shipping information at this time
 Q4. Can order be placed again once cancelled? No, items will have to be added back to their cart
 Q5. Can an order be cancelled over the phone? - Yes, we will include this in the FAQ page in Sprint 2

**Comment by neelusingh28** [comment]
User should able to cancel an order if order status is “Pending” - What does pending mean? 
Claire responded - Pending indicates that the item has been ordered but the payment has not been confirmed. So they should still be able to cancel.
Since we're not shipping anything in the prototype, in a real world example, pending would indicate the item has not shipped.

**Comment by neelusingh28** [comment]
Q6. If order status is confirmed/shipped/delivered - Will system give error message something like that this order cannot be cancelled since order status is confirmed/shipped/delivered?
Q7. Once cancelled successfully, system sent notification email to user’s email in order details - Will user receive the email in the inbox OR in order details section? I think order details section will only change the order status as 'Canceled'?

**Comment by ClaireReinken** [comment]
See below.

Claire Reinken, AM.PMP
Senior Proposal Manager

office   | 443.472.4613
fax       | 410.715.6538
email   |  claire.reinken@FEIsystems.com<mailto:claire.reinken@FEIsystems.com>
FEi Systems
9755 Patuxent Woods Drive, Suite 300 Columbia, MD 21046 |  www.FEIsystems.com<http://www.feisystems.com/>

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues  #98 and #99

**Comment by ClaireReinken** [comment]
The authorized user should be able to cancel an order when it's between pending and confirmed. The order history should then confirmed it's cancelled. I think we should wait 10 minutes for the order to change from pending to confirmed.
